name: PILOTS DIRECT
favicon: null
layout_spectrum: 0.00132
typography_spectrum: 0.80074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.48245030315592885
  saturation: 0.42904998641461134
  rhythmicContrast: 0.75
purpose: []
