name: PILOTS DIRECT
favicon: null
layout_spectrum: 0.9245286313816905
typography_spectrum: 0.1432692774105817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#b1b1b3'
    - '#164690'
    - '#5f90d3'
    - '#081362'
  brandStrength: 0.31817380036227405
  lightness: 0.48245030315592885
  saturation: 0.42904998641461134
  rhythmicContrast: 0.8434803371783346
purpose: []
